### ISSUE TITLE
Error in the gnn_solution.ipynb file

### ISSUE THREAD

**Issue by Zhyravlev-Dmitry** [airi-industrial-ai/gnn-cloud-manufacturing#2]
The gnn-cloud-manufacturing /notebooks/gnn_solution.ipynb file contains the following error:

with torch.no_grad():
2 prob = model(graph)
----> 3 v, u = model.dec.sample(graph, prob)
'DotProductDecoder' object has no attribute 'sample'.

This class is declared in the file gnn-cloud-manufacturing/cloudmanufacturing/graphconv.py

**Comment by vpozdnyakov** [comment]
@Zhyravlev-Dmitry в этом ноутбуке лежал черновик архитектуры GNN, сейчас он уже устарел и не нужен. я удалил весь код из ноутбука, оставил только текстовое описание модели. ошибка возникала при сэмплировании ребер для получения решения. сейчас это реализовано не в декодере, а в самой GNN, смотри эту [строчку](https://github.com/airi-industrial-ai/gnn-cloud-manufacturing/blob/daf4e6cf47ff42caa8952c699ab06f80117d19b8/cloudmanufacturing/graphconv.py#L152C9-L152C40)
